### ISSUE TITLE
Reusing JPS solution from previous iteration

### ISSUE THREAD

**Issue by grupot3** [sikang/jps3d#5]
I'd like to use JPS on a map that is changing. Right now I'm running JPS from scratch in every map update. Is there a way to reuse the previous solution (instead of computing the entire solution from scratch)? (something similar to the idea of LPA* or D*, but using JPS).  
Is it implemented in this repo? If not, how would you recommend me to do it? 

Thanks!

**Comment by sikang** [comment]
The incremental version of JPS has not been proposed yet, and it might be much more complicated than the original LPA* or D* Lite due to the way JPS prunes and jumps. I would not recommend to do that...
