### ISSUE TITLE
terminate called after throwing an instance of 'YAML::BadFile'

### ISSUE THREAD

**Issue by Ideal-Bai** [sikang/jps3d#6]
Hello,excuse me.
when I run into this step: ./build/test_distance_map_planner_2d ../data/corridor.yaml
it occurs error: terminate called after throwing an instance of 'YAML::BadFile'
                         what():  yaml-cpp: error at line 0, column 0: bad file

how can I solve it? please

**Comment by sikang** [comment]
I guess you need to change the command a bit as: 
./build/test_distance_map_planner_2d ./data/corridor.yaml (single dot for /data/corridor.yaml)
 or go to the build/ folder and run:
./test_distance_map_planner_2d ../data/corridor.yaml

**Comment by Ideal-Bai** [comment]
> I guess you need to change the command a bit as:
> ./build/test_distance_map_planner_2d ./data/corridor.yaml (single dot for /data/corridor.yaml)
> or go to the build/ folder and run:
> ./test_distance_map_planner_2d ../data/corridor.yaml

Thank you very much!!!
