### ISSUE TITLE
关于此工程的编译问题

### ISSUE THREAD

**Issue by Takki-cd** [sikang/jps3d#7]
您好 对于此工程的编译过程没看明白 实际编译也没有成功 (小白) 可否的耽误您一点时间 详细描述一下下载工程过后如何编译吗 不明白步骤 A)是在干什么 [拜托]

**Comment by sikang** [comment]
A) 指的是用cmake来编译， 如果系统里没有ros，这个package仍然可以作为一个普通的库来使用。如果不清楚cmake的话可以看看这个：https://preshing.com/20170511/how-to-build-a-cmake-based-project/
B) 是用ros自带的catkin来编译，本质上跟A）是一样的。

**Comment by Takki-cd** [comment]
好的 谢谢你[抱拳]
